#pragma once

#define VK_PRINT_SUPPORT_INFO 0
#define VK_PRINT_INSTANCE_INFO 0
#define VK_PRINT_DEVICE_INFO 0

#define VK_PRINT_DEVICE_SUPPORT_EXTENTIONS 0

#define VK_PRINT_SELECTED_DEVICE_INFO 0

#define VK_PRINT_SUPPORT_QUEUE 0

#define VK_PRINT_SWAPCHAIN_INFO 0
#define VK_PRINT_GRAPTHICS_PIPELINE_INFO 0
#define VK_PRINT_COMMANDBUFFER_INFO 0